### ISSUE TITLE
Add ClaimExplosions Flag

### ISSUE THREAD

**Issue by sxphirus** [akdukaan/GriefPreventionFlags#15]
**Is your feature request related to a problem? Please describe.**
/ClaimExplosions is not persistent in grief prevention

**Describe the solution you'd like**
Add a ClaimExplosions flag so users have the option to add persistence to toggling on or off claim explosions

**Comment by akdukaan** [comment]
Haven't tested it myself but this should now be possible.
Download from [jenkins](https://jenkins.akiradev.xyz/job/GPFlags/lastSuccessfulBuild/)
set BlockLandClaimExplosions to false in the gp config.
Players can set the flag NoBlockExplosions to disable explosions breaking blocks in their claim.
If you wish for claim explosions to be on by default, you can set it as a default flag (/setdefaultflag) and players will be able to toggle on block explosions with /unsetclaimflag.
Let me know how it works!
