### ISSUE TITLE
Mythic Mobs Support

### ISSUE THREAD

**Issue by good3n** [akdukaan/GriefPreventionFlags#18]
If you use the `ProtectNamedMobs` flag, in combination with Mythic Mobs, if a Mythic Mob wonders into or spawns in your claim, they're invincible.

Hopefully Mythic Mob support can get added in the future to allow them to be damaged.

**Comment by akdukaan** [comment]
Added in https://github.com/akdukaan/GriefPreventionFlags/commit/043621993dc7af745bc8237d88bcf34d11448ca3.
Let me know if it works as it's untested
