### ISSUE TITLE
Flag NoEnterPlayer not working with /accesstrust public

### ISSUE THREAD

**Issue by SirvydasS** [akdukaan/GriefPreventionFlags#25]
**Describe the bug**
When claim has setting: **/accesstrust public** and **/setclaimflag NoEnterPlayer playerName**, playerName stil can enter the claim. With no **/accesstrust public** and with only NoEnterPlayer everythings works fine.

**To Reproduce**
1. Set in claim /accesstrust public.
2. Set /setclaimflag NoEnterPlayer playerName.
3. Try go in with playerName to claim
4. You can, sad.

**Expected behavior**
When the flag set is NoEnterPlayer denies the player to enter the claim regardless of other settings.

**Versions:**
 - GriefPrevention version 16.18-12-g3d0487d
 - GPFlags version 5.12.1
 - Server version Paper version git-Paper-52 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 6ea73e7)

**Comment by akdukaan** [comment]
Should be fixed with https://github.com/akdukaan/GriefPreventionFlags/commit/1de49bc7158273ce4e809204175c958273ea8cba

Download from https://jenkins.akiradev.xyz/job/GPFlags/

I havent tested it at all myself. Let me know how it works!

**Comment by SirvydasS** [comment]
Fixed, Thanks.
