### ISSUE TITLE
exiting claim with portal problem

### ISSUE THREAD

**Issue by FakEEE14** [akdukaan/GriefPreventionFlags#26]
hi
**Describe the bug**
when you in a claim that have a exitcommand or exitcommandplayer enabled and leave the claim via portal(end or nehter) that it's in the same claim, is count as leaving the claim like leaving from the border of the claim

**To Reproduce**
1. create a claim
2. set a exitcommand or exitcommandflag
3. create a portal end portal in the claim
4. enter the portal to enter the end

**Expected behavior**
player leave the claim without executing the command.

**Versions:**
 - GriefPrevention version= 16.18 build9 (16.18-9-gd75b3cd)
 - GPFlags version= 5.12.1
 - Server version= paper 1.19 build 58

**Comment by akdukaan** [comment]
This is intended. When you go through the portal, you have now left the claim so GPFlags executes any actions that were set to be executed when the player leaves the claim.
