### ISSUE TITLE
[Feature Request] Add claim-flag to disable potion effects.

### ISSUE THREAD

**Issue by KayaLambrechts** [akdukaan/GriefPreventionFlags#27]
**Is your feature request related to a problem? Please describe.**
[Players build competitions, builds that should be viewed without night vision, etc. and other players can use potions in there to either gain an unfair advantage, or get a unintended view of the area.]

**Describe the solution you'd like**
A claim-flag to disable specific effects, but also a wildcard to disable all effects, all negative effects, and all positive effects

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by akdukaan** [comment]
I added a wildcard for all effects. However, I did not create a shortcut for all positive/negative effects.

Command examples:
/setclaimflag nopotioneffects all
/setclaimflag nopotioneffects poison speed weakness

Permissions:
gpflags.bypass.nopotioneffects to bypass
gpflags.flag.nopotioneffects to set the flag

You can download the build from https://jenkins.akiradev.xyz/job/GPFlags/
I have not tested the build myself. Let me know how it works!

**Comment by KayaLambrechts** [comment]
perfect! thank you so much <3
