### ISSUE TITLE
[Suggestion] Add a flag for withers to target passive mobs

### ISSUE THREAD

**Issue by amongus9000** [akdukaan/GriefPreventionFlags#7]
I would like a flag for withers to be able to target passive mobs for farming purposes.
Right now to achieve that function, the only way is to disable ProtectAnimals or something in the GP config

**Comment by drbot7** [comment]
Would it solve your issue if I made a ProtectAnimals claimflag? You could set it to be a defaultclaimflag, and then the players who want to not protect their animals could turn off the claimflag for some of their claims.

**Comment by akdukaan** [comment]
Went another route.
Haven't tested it myself but this should now be possible.
Download from [jenkins](https://jenkins.akiradev.xyz/job/GPFlags/lastSuccessfulBuild/)
The flag AllowWitherDamage should allow withers to damage mobs.
Let me know how it works!

**Comment by amongus9000** [comment]
It works well! Thank you
